version: "3"
services:
    web:
        container_name: analyzerAnalyzerService
        build:
            dockerfile: Dockerfile
            conanalyzer: .
        depends_on:
            - db
        ports:
            - "3000:3000"
        volumes:
            - .:/server
        environment:
            - MONGO_HOST=mongodb://db:27017
            - MONGO_DB=analyzer
            - APPLICATION_SERVER_PORT=3000
            - APP_FORCE_SHUTDOWN_SECOND=30
            - CLIENT_ORIGIN=http://localhost:3000

    # Database
    db:
        container_name: analyzerAnalyzerServiceMongo
        image: mongo
        ports:
            - "27017:27017"
        restart: always
