version: "3"
services:
  web:
    container_name: textAnalyzerService
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/server
    environment:
      - MONGO_HOST=mongodb://db:27017
      - MONGO_DB=text
      - APPLICATION_SERVER_PORT=3000
      - APP_FORCE_SHUTDOWN_SECOND=30
      - CLIENT_ORIGIN=http://localhost:3000

  # Database
  db:
    container_name: textAnalyzerServiceMongo
    image: mongo
    ports:
      - "27017:27017"
    restart: always